export enum Parameter {
  // Common
  CREATION_TIME = 'CREATION_TIME',

  // Book
  BOOK_VOTERS_COUNT = 'BOOK_VOTERS_COUNT',
  BOOK_RATE_SUM = 'BOOK_RATE_SUM',
  BOOK_GENRE = 'BOOK_GENRE',
  BOOK_PAGES = 'BOOK_PAGES',
  BOOK_RELEASE = 'BOOK_RELEASE',

  // Reserved book params
  RESERVED_BOOK_RATED = 'RESERVED_BOOK_RATED',
  RESERVED_BOOK_NEWEST = 'RESERVED_BOOK_NEWEST',
  RESERVED_BOOK_OLDER = 'RESERVED_BOOK_OLDER',
  RESERVED_BOOK_LARGEST = 'RESERVED_BOOK_LARGEST',
}
