export enum TableName {
  BOOKS = 'BOOKS',
  BOOK_REVIEWS = 'BOOK_REVIEWS',
  BOOK_OVERVIEWS = 'BOOK_OVERVIEWS',
  REVIEW_COMMENTS = 'REVIEW_COMMENTS',
  MESSAGES = 'MESSAGES',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  FRIENDS = 'FRIENDS',
  ACHIEVEMENTS = 'ACHIEVEMENTS'
}
