export enum TableName {
  'BOOKS',
  'USERS',
  'BOOK_REVIEWS',
  'BOOK_OVERVIEWS',
  'REVIEW_COMMENTS',
  'MESSAGES',
  'ANNOUNCEMENTS',
  'ACTIVITIES',
  'FRIENDS',
  'ACHIEVEMENTS',
}

//
// BOOKS = 'BOOKS',
//   USERS = 'USERS',
//   BOOK_REVIEWS = 'BOOK REVIEWS',
//   BOOK_OVERVIEWS = 'BOOK OVERVIEWS',
//   REVIEW_COMMENTS = 'COMMENTS',
//   MESSAGES = 'MESSAGES',
//   ANNOUNCEMENTS = 'ANNOUNCEMENTS',
//   ACTIVITIES = 'ACTIVITIES',
//   FRIENDS = 'FRIENDS',
//   ACHIEVEMENTS = 'ACHIEVEMENTS'
