export enum TableName {
  BOOKS = 'BOOKS',
  USERS = 'USERS',
  BOOK_REVIEWS = 'BOOK REVIEWS',
  BOOK_OVERVIEWS = 'BOOK OVERVIEWS',
  REVIEW_COMMENTS = 'COMMENTS',
  MESSAGES = 'MESSAGES',
  ANNOUNCEMENTS = 'ANNOUNCEMENTS',
  ACTIVITIES = 'ACTIVITIES',
  FRIENDS = 'FRIENDS',
  ACHIEVEMENTS = 'ACHIEVEMENTS'
}
